In [1]:
# tensorflow运算
import numpy as np
import tensorflow as tf

In [17]:
a = tf.constant(10)
a

<tf.Tensor 'Const_14:0' shape=() dtype=int32>

In [7]:
# 两个 标量 的 运算
x = tf.constant(10)
y = tf.constant(20)
# x*y
mul = tf.multiply(x,y)  # 这里其实并没有运算 只是产生了一个运算对象
div = tf.div(x,y) 

In [8]:
div

<tf.Tensor 'div:0' shape=() dtype=int32>

In [9]:
# 想要运算 想要输出数据 还是需要创建session对象

In [10]:
sess = tf.Session()

In [ ]:
sess.close()

In [13]:
# 代码执行完成之后 会自动被调用close方法
with tf.Session() as sess:
    print(sess.run(mul))
    print(sess.run(div))

200
0


In [14]:
# 矩阵的运算

In [ ]:
# 先来个简单的 先创建两个固定的 矩阵 然后要让他们相乘

In [19]:
x = tf.constant(np.random.randint(0,10,size=(3,2)))  # 2阶张量 前面是x行y列 后面是m行n列  m必须和y相等 最后的结果是 x行n列
y = tf.constant(np.random.randint(0,10,size=(2,8)))

matm = tf.matmul(x,y)  # mat matrix 矩阵 mul multiply乘法 矩阵的乘法要用matmul

In [22]:
x

<tf.Tensor 'Const_17:0' shape=(3, 2) dtype=int32>

In [21]:
with tf.Session() as sess:
    print(sess.run(matm))

[[51 77  8 61 44 47 67 29]
 [62 82 16 66 40 54 62 34]
 [30 54  0 42 36 30 54 18]]


In [26]:
# 常量是不变的数据
# 想要使用 可以改变的数据 需要使用 placeholder 占位
# 参数 dtype指定数据类型 shape指定数据的形状
x = tf.placeholder(dtype=tf.float16,shape=(3,2))
y = tf.placeholder(dtype=tf.float16,shape=(2,4))
matm = tf.matmul(x,y)

In [29]:
# 如果使用了placeholder去占位 没有传入具体数据 就需要在这里传入具体数据了
with tf.Session() as sess:
    print(sess.run(matm,feed_dict={
        x:np.random.randint(0,10,size=(3,2)),
        y:np.random.randint(0,10,size=(2,4))
    }))

[[ 58.  28. 105.  17.]
 [ 42.  42.  90.  18.]
 [ 55.  49. 114.  22.]]


In [30]:
x = tf.placeholder(dtype=tf.float16,shape=(None,2))  # 可以只规定一部分
y = tf.placeholder(dtype=tf.float16,shape=(2,None))
matm = tf.matmul(x,y)


In [34]:
with tf.Session() as sess:
    print(sess.run(matm,feed_dict={
        x:np.random.randint(0,10,size=(8,2)),
        y:np.random.randint(0,10,size=(2,3))
    }))

[[25. 35. 27.]
 [51. 63. 57.]
 [30. 35. 34.]
 [54. 42. 66.]
 [14.  7. 18.]
 [53. 14. 71.]
 [16. 28. 16.]
 [28. 49. 28.]]
