In [88]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# pandas的拼接操作

pandas的拼接分为两种：

- 级联：pd.concat, pd.append (没有重复数据)
- 合并：pd.merge, pd.join (有重复数据)

## 0. 回顾numpy的级联

============================================

练习12：

1. 生成2个3*3的矩阵，对其分别进行两个维度上的级联

============================================

In [3]:
# 留着
nd1 = np.random.randint(0,10,size=(3,3))
nd1

array([[0, 2, 1],
       [9, 0, 9],
       [4, 6, 1]])

In [4]:
# 留着
nd2 = np.random.randint(0,10,size=(3,3))
nd2

array([[6, 4, 9],
       [8, 5, 6],
       [0, 8, 3]])

In [90]:
np.concatenate((nd1,nd2))
np.concatenate((nd1,nd2),axis=1)

array([[0, 2, 1, 6, 4, 9],
       [9, 0, 9, 8, 5, 6],
       [4, 6, 1, 0, 8, 3]])

## 1. 使用pd.concat()级联

为方便讲解，我们首先定义两个DataFrame：

In [95]:
# 留着
df1 = DataFrame(nd1)
df1

0  1  2
0  0  2  1
1  9  0  9
2  4  6  1

In [96]:
# 留着
df2 = DataFrame(nd2)
df2

0  1  2
0  6  4  9
1  8  5  6
2  0  8  3

### 1)  简单级联

pandas使用pd.concat函数，与np.concatenate函数类似

In [98]:
# objs 就是 要拼接的df
df3 = pd.concat((df1,df2))
df3

0  1  2
0  0  2  1
1  9  0  9
2  4  6  1
0  6  4  9
1  8  5  6
2  0  8  3

In [99]:
df3.loc[0]  # 因为两个df的行名有重复的 所以 按照重复的行名 去检索 获得了两行

0  1  2
0  0  2  1
0  6  4  9

In [101]:
# ignore_index=False 忽略原来的索引 重新分配索引 默认是False
df3 = pd.concat((df1,df2),ignore_index=True)
df3

0  1  2
0  0  2  1
1  9  0  9
2  4  6  1
3  6  4  9
4  8  5  6
5  0  8  3

In [105]:
#  axis=0 控制拼接的方向 默认是0 是 纵向拼接
df3 = pd.concat((df1,df2),axis=0)
df3 = pd.concat((df1,df2),axis=1)
df3 = pd.concat((df1,df2),axis=1,ignore_index=True)
df3

0  1  2  3  4  5
0  0  2  1  6  4  9
1  9  0  9  8  5  6
2  4  6  1  0  8  3

### 2) 不匹配级联

不匹配指的是级联的维度的索引不一致。例如纵向级联时列索引不一致，横向级联时行索引不一致

有3种连接方式：

- 外连接：补NaN（默认模式）

- 内连接：只连接匹配的项

- 指定连接轴 join_axes

In [106]:
# 留着
df3 = DataFrame(data=nd1,columns=list('abc'))
df4 = DataFrame(data=nd2,columns=list('bcd'))
display(df3,df4)

a  b  c
0  0  2  1
1  9  0  9
2  4  6  1

b  c  d
0  6  4  9
1  8  5  6
2  0  8  3

In [112]:
# pd.concat((df3,df4))  # 警告 
pd.concat((df3,df4),sort=False)  # 对不上的列 补NaN

a  b  c    d
0  0.0  2  1  NaN
1  9.0  0  9  NaN
2  4.0  6  1  NaN
0  NaN  6  4  9.0
1  NaN  8  5  6.0
2  NaN  0  8  3.0

In [116]:
#  join='outer' join用来控制拼接方式 默认outer外联（有的都要） 还 可以 设置 inner （保留相同的列）
pd.concat((df3,df4),sort=False)
pd.concat((df3,df4),join='outer',sort=False)
pd.concat((df3,df4),join='inner',sort=False)

b  c
0  2  1
1  0  9
2  6  1
0  6  4
1  8  5
2  0  8

In [117]:
df3.columns

Index(['a', 'b', 'c'], dtype='object')

In [119]:
# 另外还可以自己制定拼接那些列
# join_axes=None 可以设定 按照那些列去拼接
pd.concat((df3,df4),join_axes=[df3.columns])
# 还可以自己制定列
index = pd.Index(['b','c'])
pd.concat((df3,df4),join_axes=[index])

b  c
0  2  1
1  0  9
2  6  1
0  6  4
1  8  5
2  0  8

In [122]:
# objs, axis=0, join='outer', join_axes=None, ignore_index=False
# objs 传入要拼接的 df
# axis 是 拼接的方向
# join 设定拼接的方式 有inner内联 和 outer外联
# join_axes 用来指定 按照哪些列去拼接
# ignore_index 忽略原来的索引 重新建立索引
# pd.concat()

============================================

练习13：

1. 假设新增考试学科"计算机"，如何实现？

2. 新增王老五同学的成绩，如何实现？

============================================

In [132]:
# 留着
index = ['张三','李四']
columns = ['python','java','c']
data = np.random.randint(0,150,size=(2,3))
df1 = DataFrame(data=data,index=index,columns=columns)
df1

python  java    c
张三      91    36   45
李四     149     3  145

In [125]:
index = ['张三','李四']
columns = ['computer']
data = np.random.randint(0,150,size=(2,1))
df2 = DataFrame(data=data,index=index,columns=columns)
df2

computer
张三        29
李四        51

In [128]:
pd.concat((df1,df2),axis=1,sort=False)

python  java    c  computer
张三      96    11  103        29
李四     125   120   86        51

In [129]:
df1

python  java    c
张三      96    11  103
李四     125   120   86

In [131]:
index = ['王老五']
columns = ['python','java','c']
data = np.random.randint(0,150,size=(1,3))
df3 = DataFrame(data=data,index=index,columns=columns)
df3

python  java    c
王老五      56    16  142

In [133]:
pd.concat((df1,df3))

python  java    c
张三       91    36   45
李四      149     3  145
王老五      56    16  142

### 3) 使用append()函数添加

由于在后面级联的使用非常普遍，因此有一个函数append专门用于在后面添加

In [134]:
df1

python  java    c
张三      91    36   45
李四     149     3  145

In [135]:
df3

python  java    c
王老五      56    16  142

In [136]:
df1.append(df3)

python  java    c
张三       91    36   45
李四      149     3  145
王老五      56    16  142

============================================

练习15： 新建一个只有张三李四王老五的期末考试成绩单ddd3，使用append()与期中考试成绩表ddd级联

============================================

In [139]:
# 留着
index = ['张三','李四','王五']
columns = ['python','java','c']
data = np.random.randint(0,150,size=(3,3))
df5 = DataFrame(data=data,index=index,columns=columns)
df5

python  java    c
张三     136    54  145
李四       6    75   50
王五      50    30   17

In [141]:
index = ['张三','李四','王五']
columns = ['python','java','c']
data = np.random.randint(0,150,size=(3,3))
df6 = DataFrame(data=data,index=index,columns=columns)
df6

python  java   c
张三     130     3   3
李四      26   134  52
王五      72    16  12

In [142]:
df5.append(df6)

python  java    c
张三     136    54  145
李四       6    75   50
王五      50    30   17
张三     130     3    3
李四      26   134   52
王五      72    16   12

## 2. 使用pd.merge()合并

merge与concat的区别在于，merge需要依据某一共同的行或列来进行合并

注意每一列元素的顺序不要求一致

###  1) 一对一合并

### 2) 多对一合并

### 3) 多对多合并

t1 = pd.read_excel('./data/demo.xls',sheet_name=0)

t2 = pd.read_excel('./data/demo.xls',sheet_name=1)

t3 = pd.read_excel('./data/demo.xls',sheet_name=2)

t4 = pd.read_excel('./data/demo.xls',sheet_name=3)

t5 = pd.read_excel('./data/demo.xls',sheet_name=4)

In [145]:
t1 = pd.read_excel('./data/demo.xls',sheet_name=0)
# t1
t2 = pd.read_excel('./data/demo.xls',sheet_name=1)
t3 = pd.read_excel('./data/demo.xls',sheet_name=2)
t4 = pd.read_excel('./data/demo.xls',sheet_name=3)
t5 = pd.read_excel('./data/demo.xls',sheet_name=4)

In [150]:
# 一对一
# left, right 指定是 传入的两个 要拼接的表格
#  how='inner' 怎样融合数据 默认inner 两个表格都有的才要 {'left', 'right', 'outer', 'inner'}
pd.merge(t1,t2)  # 默认值是inner
pd.merge(t1,t2,how='inner')  # 两个都有的才要
pd.merge(t1,t2,how='outer')  # 两个表格里的都要
pd.merge(t1,t2,how='left')  # 以左边的为准
pd.merge(t1,t2,how='right')  # 以右边的为准

手机型号    参考价格    重量
0  windowsPhone  2500.0  0.50
1        iPhone  7500.0  0.40
2       Android  4000.0  0.45
3         other     NaN  0.60

In [156]:
# 一对多
# pd.merge(t1,t3)  # inner把两个表格都有的项目作乘积
pd.merge(t1,t3,how='outer')  # 任何表格有的项目 都拿出来 然后做乘积
pd.merge(t1,t3,how='left')  # 以左侧的内容 为准 作乘积
pd.merge(t1,t3,how='right')  # 以右侧的内容 为准 作乘积

手机型号  参考价格     经销商       发货地区
0  windowsPhone  2500  petter   shenzhen
1        iPhone  7500   pegge    beijing
2        iPhone  7500     tom  guangzhou
3       Android  4000    lucy    beijing
4       Android  4000    mery  guangzhou

In [168]:
# 多对多
# display(t3,t4)
# pd.merge(t3,t4,how='right',on='手机型号')  # on用来指定按照哪一列来拼接
# pd.merge(t3,t4,how='right',on='手机型号',suffixes=('_上半年', '_下半年')) 
# pd.merge(t3,t4,how='right',on=['手机型号','发货地区'])

经销商       发货地区          手机型号    价格
0   pegge    beijing        iPhone  7000
1    lucy    beijing       Android  3600
2     tom  guangzhou        iPhone  7600
3  petter   shenzhen  windowsPhone  2750
4    mery  guangzhou       Android  4200
5     NaN    beijing  windowsPhone  2300
6     NaN  guangzhou  windowsPhone  2800
7     NaN   shenzhen        iPhone  7400
8     NaN   shenzhen       Android  3900

In [169]:
t7 = pd.read_excel('./data/demo.xls',sheet_name=6)
t7

学生姓名  班级id
0     张三     1
1     李四     1
2     王五     1
3    tom     2
4  jerry     2
5    bob     2

In [171]:
t8 = pd.read_excel('./data/demo.xls',sheet_name=7)
t8

老师  班级id
0  jfeng     1
1  jfeng     2
2     班长     1
3     班长     2

In [174]:
pd.merge(t7,t8,on='班级id')

学生姓名  班级id     老师
0      张三     1  jfeng
1      张三     1     班长
2      李四     1  jfeng
3      李四     1     班长
4      王五     1  jfeng
5      王五     1     班长
6     tom     2  jfeng
7     tom     2     班长
8   jerry     2  jfeng
9   jerry     2     班长
10    bob     2  jfeng
11    bob     2     班长